import { readHtml, findVotes } from './index'

describe('loading html', () => {
  it('should get text', async () => {
    const html = await readHtml(`${__dirname}/../test/hans-deb-test.html`)
    expect(html).toBeTruthy()
    expect(html.indexOf('New Zealand Parliament')).toBeGreaterThan(0)
  })
})

describe('findVotes', () => {
  it('should find 2 votes', async () => {
    const html = await readHtml(`${__dirname}/../test/hans-deb-test.html`)
    const votes = findVotes(html)
    expect(votes.length).toEqual(2)
    expect(votes).toEqual([
      {
        cast: [
          { name: 'Adams', present: false },
          { name: 'Ghahraman', present: true },
          { name: 'Mallard', present: false },
          { name: 'Tinetti', present: true },
          { name: 'Andersen', present: true },
          { name: 'Henare', present: true },
          { name: 'Nash', present: false },
          { name: 'Wall', present: false },
          { name: 'Bennett P', present: true },
          { name: 'Hipkins', present: true },
          { name: 'Prime', present: false },
          { name: 'Warren-Clark', present: false },
          { name: 'Clark', present: true },
          { name: 'Hughes', present: true },
          { name: 'Radhakrishnan', present: false },
          { name: 'Webb', present: true },
          { name: 'Coffey', present: true },
          { name: 'Huo', present: true },
          { name: 'Robertson', present: true },
          { name: 'Williams', present: false },
          { name: 'Collins', present: true },
          { name: 'Kaye', present: true },
          { name: 'Ross', present: true },
          { name: 'Yang', present: true },
          { name: 'Craig', present: true },
          { name: 'Kuriger', present: false },
          { name: 'Russell', present: true },
          { name: 'Curran', present: true },
          { name: 'Lees-Galloway', present: true },
          { name: 'Sage', present: true },
          { name: 'Doocey', present: false },
          { name: 'Little', present: false },
          { name: 'Shaw', present: true },
          { name: 'Dyson', present: false },
          { name: 'Logie', present: false },
          { name: 'Sio', present: true },
          { name: 'Eagle', present: true },
          { name: 'Lubeck', present: false },
          { name: 'Stanford', present: false },
          { name: 'Genter', present: true },
          { name: 'Luxton', present: true },
          { name: 'Swarbrick', present: true },
          { name: 'Davidson', present: false },
        ],
        reason:
          'A personal vote was called for on the question, That the motion be agreed to.',
        result: 'Motion not agreed to.',
        type: 'Ayes',
        count: 43,
      },
      {
        cast: [
          { name: 'Allan', present: true },
          { name: 'Guy', present: true },
          { name: 'Mitchell M', present: true },
          { name: 'Smith S', present: false },
          { name: 'Ardern', present: true },
          { name: 'Hayes', present: true },
          { name: 'Muller', present: true },
          { name: 'Strange', present: false },
          { name: 'Bakshi', present: true },
          { name: 'Hipango', present: true },
          { name: 'Ngaro', present: false },
          { name: 'Tabuteau', present: true },
          { name: 'Ball', present: true },
          { name: 'Hudson', present: false },
          { name: "O'Connor D", present: true },
          { name: 'Tirikatene', present: true },
          { name: 'Barry', present: true },
          { name: 'Jackson', present: true },
          { name: "O'Connor G", present: false },
          { name: 'Tolley', present: false },
          { name: 'Bayly', present: false },
          { name: 'Jones', present: true },
          { name: "O'Connor S", present: false },
          { name: 'Twyford', present: true },
          { name: 'Bennett D', present: true },
          { name: "Kanongata'a-Suisuiki", present: true },
          { name: 'Parker', present: true },
          { name: 'van de Molen', present: false },
          { name: 'Bidois', present: false },
          { name: 'King', present: false },
          { name: 'Parmar', present: true },
          { name: 'Wagner', present: true },
          { name: 'Bishop', present: true },
          { name: 'Lee D', present: false },
          { name: 'Patterson', present: true },
          { name: 'Walker', present: true },
          { name: 'Bridges', present: true },
          { name: 'Lee M', present: false },
          { name: 'Penk', present: false },
          { name: 'Whaitiri', present: true },
          { name: 'Brown', present: false },
          { name: 'Loheni', present: false },
          { name: 'Peters', present: true },
          { name: 'Willis', present: true },
          { name: 'Brownlee', present: false },
          { name: 'Macindoe', present: false },
          { name: 'Pugh', present: true },
          { name: 'Wood', present: false },
          { name: 'Carter', present: false },
          { name: 'Mahuta', present: true },
          { name: 'Reti', present: true },
          { name: 'Woodhouse', present: false },
          { name: 'Davis', present: true },
          { name: 'Marcroft', present: true },
          { name: 'Rurawhe', present: false },
          { name: 'Young', present: true },
          { name: 'Dean', present: true },
          { name: 'Mark', present: true },
          { name: 'Salesa', present: true },
          { name: 'Yule', present: true },
          { name: 'Dowie', present: true },
          { name: 'Martin', present: true },
          { name: 'Scott', present: true },
          { name: 'Faafoi', present: true },
          { name: 'McAnulty', present: false },
          { name: 'Sepuloni', present: true },
          { name: 'Falloon', present: false },
          { name: 'McClay', present: true },
          { name: 'Seymour', present: false },
          { name: 'Garcia', present: false },
          { name: 'McKelvie', present: false },
          { name: 'Simpson', present: false },
          { name: 'Goldsmith', present: true },
          { name: 'Mitchell C', present: false },
          { name: 'Smith N', present: false },
          { name: 'Upston', present: false },
        ],
        reason:
          'A personal vote was called for on the question, That the motion be agreed to.',
        result: 'Motion not agreed to.',
        type: 'Nays',
        count: 76,
      },
    ])
  })
})
